### PR TITLE
Fixed link for the .delete() method in Storage class

### PR DESCRIPTION
**Pull request by Padmanabhan100**
There is an issue in the Google Storage API link

### CODE REVIEW

**Comment by felixtigges** [comment]
Since the new version (4.8.0), my code no longer works due to these changes. When I reset the changes, my code works again. 

I get the following error message when I use version 4.8.0:

Traceback (most recent call last):
  File "/Users/felixtigges/Applications/tf/tfWebsite/api/venv/lib/python3.9/site-packages/pyrebase/pyrebase.py", line 544, in raise_detailed_error
    request_object.raise_for_status()
  File "/Users/felixtigges/Applications/tf/tfWebsite/api/venv/lib/python3.9/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://firebasest **{URL...}** ern.appspot.com/o/?name=ztest_Checklists/errorlist/templates/2024/8/7/1723018253574.json
...
File "/Users/felixtigges/Applications/tf/tfWebsite/api/venv/lib/python3.9/site-packages/pyrebase/pyrebase.py", line 504, in delete
    raise_detailed_error(request_object)
  File "/Users/felixtigges/Applications/tf/tfWebsite/api/venv/lib/python3.9/site-packages/pyrebase/pyrebase.py", line 548, in raise_detailed_error
    raise HTTPError(e, request_object.text)
requests.exceptions.HTTPError: [Errno 400 Client Error: Bad Request for url: https://firebasest **{URL...}** ern.appspot.com/o/?name=ztest_Checklists/errorlist/templates/2024/8/7/1723018253574.json] {
  "error": {
    "code": 400,
    "message": "Invalid HTTP method/URL pair."
  }
}


If I manually remove the change, the code will work again and my files can be deleted.

**Comment by nhorvath** [comment]
what does your inputs to the delete method look like?

**Comment by felixtigges** [comment]
storage_path = "ztest_Checklist/2024/08/07/2131980.json"
storage.delete(storage_path, "")

**Comment by nhorvath** [comment]
I think you're correct, but Google no longer publishes the url api docs so I can't be sure. I'm going to revert this pr.

**Pull request merged**
